* لماذا نحن بحاجة لتقسية فايرفوكس؟
رغم أن فايرفوكس أفضل من كروم بكثير فيما يخص خصوصيتك، إلا أنه ليس جيداً بشكل كافي بعد تثبيته مباشرة، حيث أن فايرفوكس يقوم بجمع البيانات و إرسال تقارير عن الأخطاء إلى موزيلا، و هنالك العديد من خصائص الخصوصية غير المفعلة بشكل مسبق.

يمكننا تعطيل جمع البيانات و إرسال التقارير و ايقاف قدر كبير من ميزات التعقب مما يسمح لنا بالحصول على تصفح أكثر خصوصية.

* قبل البدء
هذا الدليل قد تمت كتابته للإصدار الأخير من فايرفوكس و تم اختباره على فايرفوكس 101.

لا تنسى تحديث فايرفوكس إلى الإصدار الأخير قبل اتباع الخطوات المذكورة هنا.

إذا رأيت أي خيار في هذا الدليل غير موجود في نسخة فايرفوكس التي تستخدمها يمكنك تجاهله.

* تغيير إعدادات فايرفوكس
** تغيير محرك البحث الافتراضي
أنا شخصياً أفضل استخدام محرك البحث Startpage لإنه يقدم نفس نتائج البحث التي نحصل عليها من جوجل لكن دون أن تقوم جوجل بتتبعنا و جمع بيانات البحث الخاصة بنا.

لاستخدام Startpage سنقوم بعد قليل بتثبيت الإضافة الخاصة به و ستتكفل الإضافة بتغيير المحرك.
** تفعيل الحماية من التتبع
من قسم الخصوصية و الأمان نذهب إلى قسم الحماية من التتبع المحسن و نختار مخصص، نقوم بتحديد كافة الخيارات و نختار كافة كوكيز الطرف الثالث من قسم الكوكيز. هذا قد يتسبب في توقف بعض المواقع عن العمل، لكنها خطوة ضرورية للأمان و الخصوصية.

إذا وجدت أحد المواقع لا يعمل بدون كوكيز الطرف الثالث فيمكننا تعطيل الحماية من التعقب بشكل مؤقت لهذا الموقع. و ذلك بالذهاب إلى شريط العنوان في أعلى النافذة و الضغط على زر الدرع و إيقاف الحماية المحسنة لهذا الموقع.
** تعطيل حفظ كلمات السر
في ذات الصفحة، تحت قسم تسجيل الدخول و كلمات السر، نقوم بإزالة التحديد عن خيار حفظ تسجيل الدخول و كلمات السر للمواقع. حفظ كلمات السر في المتصفح ليس من العادات الجيدة و بدلاً عن ذلك فإنه من الأفضل استخدام مدير كلمات سر.
** رفض الوصول إلى الموقع الجغرافي
في ذات الصفحة، في إعدادات الموقع الجغرافي، نقوم بتحديد حظر الطلبات الجديدة التي تسأل عن السماح بالوصول للموقع الجغرافي. هذا من شأنه أن يرفض الرسالة الخاصة بأذونات الوصول إلى الموقع الجغرافي لكن إمكانية تحديد الموقع الجغرافي ما زالت مفعلة و سنهتم بها لاحقاً.
** تعطيل التنبيهات
في ذات الصفحة، نقوم بتحديد خيار حجب الطلبات الجديدة التي تسأل عن السماح بالتنبيهات. هذا من سأنه أن يرفض الرسالة الخاصة بأذونات التنبيهات لكن إمكانية التنبيهات ما زالت مفعلة و سنهتم بها لاحقاً.
** عدم السماح بالتشغيل التلقائي
في ذات الصفحة في، في إعدادات التشغيل التلقائي، نقوم بتغيير "الافتراضي لكافة المواقع" إلى حظر الصوت و الفيديو.
** تعطيل جمع البيانات و إرسال تقارير الأخطاء
في ذات الصفحة، نقوم بإزالة التحديد عن كل ما يتعلق بجمع البيانات
** تفعيل وضع HTTPS-Only
في ذات الصفحة، نقوم بتفعيل خيار HTTPS-Only لكافة النوافذ.
HTTPS تقوم بتقديم اتصالات مشفرة بين المتصفح و مواقع الويب، و هذا ما ينبغي أن نستخدمه إذا كان متاحاً.

عند تفعيل هذا الخيار فإن فايرفوكس يقوم بترقية كافة الاتصالات إلى HTTPS و تظهر رسالة تحذير عند محاولة الولوج إلى أحد المواقع التي لا تدعم هذا البروتوكول.
* الخيارات المتقدمة
للوصول إلى الخيارات المتقدمة نقوم بإدخال about:config في شريط العنوان و عند ظهور شاشة التحذير نضغط على قبول الخطر للمتابعة.

في هذه الصفحة، جميع الخيارات مرتبة أبجدياً، و يمكن البحث عن الخيار الذي نريده باستخدام خانة البحث في الأعلى. في هذا القسم، يتم تعليم العناصر التي نقوم بتغييرها و قيمتها الجديدة تظهر بخط داكن.

لتغيير قيمة أحد العناصر نقوم بالضغط المزدوج عليها. إذا كان العنصر عن قيمة منطقية فإن النقر المزدوج عليها يقوم بتغيير القيمة من =true= إلى =false= أو العكس. أما إذا كان العنصر عبارة عن عدد صحيح فإن النقر المزدوج يسمح لنا بإدخال القيمة الجديدة.

ملاحظة: العديد من الخيارات التي سيتم ذكرها أدناه من المفترض ألا يكون لها أي تأثير على أداء فايرفوكس و هي بالتأكيد مفيدة للجميع. على الرغم من ذلك، بعض هذه الخيارات قد تعطل بعض الوظائف التي قد يحتاجها بعض المستخدمين.

في القسم التالي سنقوم بتقسيم الخطوات إلى ثلاث مستويات حسب مقدار تأثيرها على تجربة المستخدم النهائية. حيث أن المستوى الأول هو مجموعة من الخيارات التي ينصح بها لكافة المستخدمين. في حين أن المستوى الثاني هو مجموعة من الخيارات التي قد تسبب بعض المشاكل البسيطة خلال تصفح الانترنت. أما المستوى الثالث فهو للمستخدمين المتقدمين و يجب التعامل معه بحرص شديد.
من المفضل تثبيت إضافة =Privacy Settings= التي تسمح بتغيير بعض الخصائص بشكل مؤقت مما يسمح للمواقع بالعمل بشكل طبيعي.
** المستوى الأول
*** تعطيل جمع البيانات
- نقوم بتبديل =browser.newtabpage.activity-stream.feeds.telemetry= إلى =false=
- نقوم بتبديل =browser.ping-centre.telemetry= إلى =false=
- نقوم بتبديل =browser.tabs.crashReporting.sendReport= إلى =false=
- نقوم بتبديل =devtools.onboarding.telemetry.logged= إلى =false=
- نقوم بتبديل =toolkit.telemetry.enabled= إلى =false=
- نحذف الرابط من =toolkit.telemetry.server= و نتركه فارغاً.
- نقوم بتبديل =toolkit.telemetry.unified= إلى =false=

*** تعطيل Pocket
إذا لم تكن تستخدم Pocket، أو إذا لم تكن تريد أن يقوم فايرفوكس بدمج Pocket، فيمكنك القيام بهذه التغييرات:
- نقوم بتبديل =browser.newtabpage.activity-stream.feeds.discoverystreamfeed= إلى =false=
- نقوم بتبديل =browser.newtabpage.activity-stream.feeds.section.topstories= إلى =false=
- نقوم بتبديل =browser.newtabpage.activity-stream.section.highlights.includePocket= إلى =false=
- نقوم بتبديل =browser.newtabpage.activity-stream.showSponsored= إلى =false=
- نقوم بتبديل =extensions.pocket.enabled= إلى =false=

*** تعطيل التحميل المسبق Prefetching
على الرغم من أن التحميل المسبق قد يساعد على تسريع بعض الأشياء، إلا أنه قد يقوم بالإتصال بالمخدمات دون تدخل من المستخدم (الذي قد يكون مشكلة بالنسبة للخصوصية) و فوائد الأداء التي سنحصل عليها ضئيلة، لذا فإن القيام بهذه التغييرات من شأنه تعطيل التحميل المسبق:
- نقوم بتبديل =network.dns.disablePrefetch= إلى =true=
- نقوم بتبديل =network.prefetch-next= إلى =false=

*** تعطيل جافا في ملفات PDF
فايرفوكس 88 قام بإضافة القدرة على تنفيذ سكريبتات جافا في مستندات PDF. رغم أنه هنالك بعض الاستخدامات الجيدة لهذه السكريبتات (كالقيام بمصادقة الصيغ)، إلا أن هذه الاستخدامات ليس شائعة. بالإضافة إلى أنه يمكن استخدام هذه السكريبتات لأغراض خبيثة، و لذلك فإنه من المستحسن أن نقوم بتعطيل هذه الخاصية.
لتعطيل هذه الميزة نقوم بتغيير =pdfjs.enableScripting= إلى =false=.

*** تقسية تفضيلات SSL
القيام بهذه التغييرات سيقوم بتعطيل تشفير SSL غير الآمن و إجبار التفاوض الآمن:
- نقوم بتبديل =security.ssl.require_safe_negotiation= إلى =true=
ملاحظة:
هناك عدد قليل من المواقع التي قد تتوقف عن العمل بعد إجراء هذا التغيير. إذا واجهتك هذه المشكلة يمكنك ترك هذا الخيار على وضعه الإفتراضي و تغيير =security.ssl.treat_unsafe_negotiation_as_broken= إلى =true=.

*** تعطيل ميزات حساب فايرفوكس
إذا لم  تكن تريد مزامنة بيانات المتصفح مع حساب فايرفوكس، فبكل بساطة يمكنك ألا تقوم بتسجيل الدخول إلى حسابك.
أما بالنسبة للأشخاص الذين يريدون تعطيل هذه الميزة بالكامل فنقوم بتغيير =identity.fxaccounts.enabled= إلى =false=.

** المستوى الثاني
*** تعطيل دعم الموقع الجغرافي
هذا من شأنه أن يمنع المواقع من  الوصول إلى معلومات موقعك الجغرافي. للقيام بذلك نقوم بتغيير =geo.enabled= إلى =false=.

يمكنك تخطي هذه الخطوة إذا كنت تنوي استخدام موقعك الجغرافي في المواقع التي تتطلب ذلك.
*** تعطيل دعم التنبيهات
التنبيهات التي تصلنا من المواقع المختلفة قد تكون مزعجة بالنسبة للبعض و ليست بتلك الفائدة، لذا لتعطيلها نقوم بتغيير  =dom.webnotifications.enabled= إلى =false=.

يمكنك تخطي هذه الخطوة إذا كنت تريد الحصول على التنبيهات من المواقع المختلفة التي تقدمها.
*** تعطيل WebRTC
من المحتمل أن يتسبب WebRTC بكشف عنوان IP الخاص بك الحقيقي، لتعطيله نقوم بتغيير التالي:
- نقوم بتغيير  =media.peerconnection.enabled= إلى =false=
- نقوم بتغيير  =media.navigator.enabled= إلى =false=
ملاحظة: هذا التغيير من المحتمل أن يتسبب في توقف بعض المواقع عن العمل و خاصة تلك التي تستخدم اتصالات الزمن الحقيقي، و هذا يتضمن أغلب برامج المحادثة و المكالمات المرئية. كن حذراً إذا كنت تستخدم هذه المواقع.
*** تعطيل WebGL
يتم استخدام WebGL في بعض تطبيقات الويب و الألعاب الأونلاين، لكنه قد بتعبر ثغرة أمان و قد يستخدم لتحديد هوية نظامك. و لذلك فلتعطيله نقوم بتغيير  =webgl.disabled= إلى =true=.

** المستوى الثالث
*** مقاومة تحديد هوية المتصفح
هذه الميزة تساهم في تقليل قدرة الناشرين و برامج التتبع على تحديد هويتك.
نقوم بتغيير =privacy.resistFingerprinting= إلى =true=.

ملاحظة: قد يتسبب تفعيل هذه الميزة إلى أثر سلبي على الأداء و الاستقرار، لذا يجب الحذر.

*** تعطيل بعض الترويسات
نقوم بتغيير =network.http.sendRefererHeader= إلى 0.
ملاحظة: العديد من المواقع التي تتطلب تسجيل الدخول تستخدم هذه الترويسات من أجل الأمان و الحماية من السبام، و إذا لم نقم بإرسال هذه الترويسات فإن الموقع لن يعمل

* تثبيت بعض الإضافات
- uBlock Origin
- Startpage protection
- A password manager
- Privacy Settings
هذه الإضافة تحدثنا في الأعلى أننا سنقوم بتثبيتها لنتمكن من تغيير إعدادات بعض المواقع إذا لم تعمل بشكل صحيح بعد قيامنا بتقسية فايرفوكس.
